#!/bin/bash

if [[ -z "$1" ]]; then
    echo "需要输入域名" && exit 0
fi

domain=$1
if ! which ~/.acme.sh/acme.sh; then
    curl https://get.acme.sh | sh -s email=my@example.com
fi

if ! which socat; then
    apt install -y socat
fi

if which nginx; then
    service nginx stop
fi

# 申请证书
~/.acme.sh/acme.sh --issue -d "$domain" --standalone

# 安装证书
mkdir -p /var/www/ssl/$domain

~/.acme.sh/acme.sh --install-cert -d $domain \
    --key-file /var/www/ssl/$domain/private.key \
    --fullchain-file /var/www/ssl/$domain/fullchain.pem

if which nginx; then
    service nginx start
fi

# echo nginx config
echo "server {
        listen 80;
        listen [::]:80;
        server_name $domain;
        rewrite ^(.*) https://\$server_name\$1 permanent;
}
server {
        listen 443 ssl;
        listen [::]:443 ssl;
        root /var/www/public;
        index index.html index.htm index.nginx-debian.html;
        server_name $domain;
        ssl_certificate /var/www/ssl/$domain/fullchain.pem;
        ssl_certificate_key /var/www/ssl/$domain/private.key;
        location / {
                try_files \$uri \$uri/ =404;
        }
}" >$domain

echo "nginx config has write to $domain"
